# Generated by Django 5.2.7 on 2025-11-03 14:59

import django.db.models.deletion
import purchases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_pan_vat_businessprofile_tax_id_and_more'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='tax_total',
            new_name='due_amount',
        ),
        migrations.RenameField(
            model_name='billitem',
            old_name='price',
            new_name='total_price',
        ),
        migrations.RenameField(
            model_name='billitem',
            old_name='total',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='notes',
        ),
        migrations.AddField(
            model_name='bill',
            name='business',
            field=models.ForeignKey(default=purchases.models.get_default_business, on_delete=django.db.models.deletion.CASCADE, to='accounts.businessprofile'),
        ),
        migrations.AddField(
            model_name='bill',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='billitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('received', 'Received'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
